### ISSUE TITLE
for insert , need function  addvalues for serveral values

### ISSUE THREAD

**Issue by xiahui1986** [Beakerboy/VBA-SQL-Library#3]

**Comment by Beakerboy** [comment]
My plan is to inspect the Values array to see if it is 2 dimensional. If so, each row would be treated as a separate set of data.

**Comment by Beakerboy** [comment]
I added a function to check the dimentions of the vValues array. If it's 2D, join it as appropriate. I added a new unit test for this case as well. Please review the unit test to make sure it suits your needs.

**Comment by xiahui1986** [comment]
Sometime there is “()" in the data ,so
 In insert need add '' in the insert string ,
And select need order function ,and thank you for your code,before I find your code,I try write by myself ,but is difficult.
 
 
 
 




 
 
 
 
 




 


 




发自网易邮箱大师
On 11/19/2018 20:16, Kevin Nowaczyk wrote:

My plan is to inspect the Values array to see if it is 2 dimensional. If so, each row would be treated as a separate set of data.

**Comment by Beakerboy** [comment]
You should use the `str()` function any time strings are being inserted into the database. For example:

    Dim TextValue as String
    TextValue = "something'()"
    MyInsert.Values = Array(str(TextValue))    'The database now sees the value as 'something''()'

The `str()` function helps prevent some types of SQL injection, but also ensures text is surrounded by single quote so it is not confused as a database field name.

I coded up ORDER BY yesterday, and will push the updates to Github shortly.

In the future, please open a new issue for each question or request instead of commenting on a closed issue. It's easier to keep track of everything, and I can have github send automatic updated when a code changes affects your issue.
